version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_CHANNEL_ID=${WEBHOOK_CHANNEL_ID}
      - MONGODB_URL={MONGODB_URL}
      - MONGODB_PORT={MONGODB_PORT}
      - MONGODB_DB={MONGODB_DB}
      - MONGODB_USER={MONGODB_USER}
      - MONGODB_PASS={MONGODB_PASS}
      - WEBHOOK_PROXY_URL={WEBHOOK_PROXY_URL}